/* eslint-disable sort-keys */

export const devicesMappings = {
  dynamic: "strict",
  properties: {
    model: {
      type: "keyword",
      fields: { text: { type: "text" } },
    },
    reference: {
      type: "keyword",
      fields: { text: { type: "text" } },
    },
    assetId: {
      type: "keyword",
      fields: { text: { type: "text" } },
    },
    engineId: {
      type: "keyword",
      fields: { text: { type: "text" } },
    },
    metadata: {
      properties: {
        // autogenerated from registered metadata
      },
    },
    measures: {
      properties: {
        // measures mappings will be injected by the plugin
      },
    },
  },
};
