import { JSONObject } from 'kuzzle';

import { BaseAssetContent } from '../types';

export class BaseAsset {
  _id: string;
  _source: BaseAssetContent;

  constructor (content: BaseAssetContent, _id?: string) {
    this._id = _id || `${content.type}_${content.model}_${content.reference}`;

    this._source = content;
  }

  serialize (): JSONObject {
    return {
      _id: this._id,
      _source: this._source
    };
  }
}

export const assetsMappings ={
  dynamic: 'strict',
  properties: {
    type: { type: 'keyword' },
    model: { type: 'keyword' },
    reference: { type: 'keyword' },
    measures: {
      properties: {
        // autogenerated from sensors mappings
      }
    },
    metadata: {
      dynamic: 'false',
      properties: {}
    }
  }
};
