/* eslint-disable sort-keys */

export const assetsMappings = {
  dynamic: "strict",
  properties: {
    model: {
      type: "keyword",
      fields: { text: { type: "text" } },
    },
    reference: {
      type: "keyword",
      fields: { text: { type: "text" } },
    },
    metadata: {
      properties: {
        // autogenerated from registered asset models
      },
    },
    measures: {
      properties: {
        // autogenerated from devices mappings
      },
    },
    deviceLinks: {
      properties: {
        deviceId: {
          type: "keyword",
          fields: { text: { type: "text" } },
        },
        measureNamesLinks: {
          properties: {
            assetMeasureName: {
              type: "keyword",
              fields: { text: { type: "text" } },
            },
            deviceMeasureName: {
              type: "keyword",
              fields: { text: { type: "text" } },
            },
          },
        },
      },
    },
  },
};
