import { metadataValue } from "../../metadata/collections/metadataMappings";

export const assetsMappings = {
  dynamic: "strict",
  properties: {
    category: {
      fields: {
        text: { type: "text" },
      },
      type: "keyword",
    },
    deviceLinks: {
      properties: {
        deviceId: {
          fields: {
            text: { type: "text" },
          },
          type: "keyword",
        },
        measureNamesLinks: {
          properties: {
            assetMeasureName: {
              fields: {
                text: { type: "text" },
              },
              type: "keyword",
            },
            deviceMeasureName: {
              fields: {
                text: { type: "text" },
              },
              type: "keyword",
            },
          },
        },
      },
    },
    measures: {
      properties: {
        // autogenerated from devices mappings
      },
    },
    metadata: metadataValue,
    model: {
      fields: {
        text: { type: "text" },
      },
      type: "keyword",
    },
    reference: {
      fields: {
        text: { type: "text" },
      },
      type: "keyword",
    },
    subCategory: {
      fields: {
        text: { type: "text" },
      },
      type: "keyword",
    },
    type: {
      fields: {
        text: { type: "text" },
      },
      type: "keyword",
    },
  },
};
