import { JSONObject } from 'kuzzle'

export interface BaseMeasure {
  /**
   * Date of the measure
   */
  updatedAt: number;

  /**
   * The payload uuid is auto-generated by Kuzzle
   */
  payloadUuid?: string;

  [property: string]: any;
};

export interface PositionMeasure extends BaseMeasure {
  point: {
    lat: number;
    lon: number;
  };

  altitude?: number;

  accuracy?: number;
}

export interface TemperatureMeasure extends BaseMeasure {
  degree: number;
}

export interface MovementMeasure extends BaseMeasure {
  moving: boolean;
}

export type Measure = BaseMeasure;

export type SensorMeasures = {
  position?: PositionMeasure;

  temperature?: TemperatureMeasure;

  movement?: MovementMeasure;

  [measureType: string]: Measure;
}

export interface BaseAssetMeasure extends BaseMeasure {
  /**
   * Sensor ID
   */
  id: string;

  /**
   * Sensor model
   */
  model: string;

  /**
   * Sensor reference
   */
  reference: string;

  /**
   * Sensor metadata
   */
  metadata: JSONObject;
}

export type AssetMeasures = {
  [measureType: string]: BaseAssetMeasure;
}
