name: Pull request checks

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  check-types:
    name: Check types
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run types tests
        run: npm run test:types

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-22.04
    needs: [lint, check-types]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: docker pull
        run: docker compose --profile backend pull
      - name: docker install dependencies
        run: docker compose run --no-deps kuzzle /bin/bash -c "npm ci"
      - name: docker backend
        run: |
          # Continue when error
          set +e
          export BACKEND_COMMAND="npm run build && npm run prod";
          docker compose --profile backend up -d --wait
          exitcode="$?"
          [[ "$exitcode" == "0" ]] || docker compose logs kuzzle
          exit "$exitcode"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:functional
