name: Pull request checks

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  check-types:
    name: Check types
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run types tests
        run: npm run test:types

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-22.04
    needs: [lint, check-types]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          docker-compose up -d
          # Start backend in background (& is mandatory to run process in background otherwise the task never continue)
          npm run dev &
          ./tests/wait-kuzzle.sh
          npm run test:functional

  # doc-dead-links:
  #   name: Check dead-links
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Extract references from context
  #       shell: bash
  #       id: extract-refs
  #       run: |
  #         echo "::set-output name=version::$(git describe --abbrev=0 --tags | cut -d. -f 1)"
  #         echo "::set-output name=repo::$(echo $GITHUB_REPOSITORY | cut -d/ -f 2)"
  #         echo "::set-output name=fw-branch::$(if [ $BASE_BRANCH == master ]; then echo master; else echo develop; fi)"
  #     - uses: convictional/trigger-workflow-and-wait@v1.3.0
  #       with:
  #         owner: kuzzleio
  #         repo: documentation
  #         github_token: ${{ secrets.ACCESS_TOKEN_CI }}
  #         workflow_file_name: dead_links.workflow.yml
  #         ref: ${{ steps.extract-refs.outputs.fw-branch }}
  #         inputs: '{"repo_name": "${{ steps.extract-refs.outputs.repo }}", "branch": "${{ github.head_ref }}", "version": "${{ steps.extract-refs.outputs.version }}"}'
