name: Push and PR

on:
  push:
    branches:
      - '[0-9]+-dev'
      - '[0-9]+-beta'
      - '[0-9]+-stable'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ['20', '22', '24']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies

        run: npm install
      - name: Run lint
        run: npm run lint --prefix plugin

  check-types:
    name: Check types
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ['20', '22', '24']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run types tests
        run: npm run test:types --prefix plugin

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ['24']
    needs: [lint, check-types]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: docker backend
        run: |
          # Continue when error
          set +e
          export NODE_VERSION=${{ matrix.node-version }}

          docker compose run --rm --no-deps kuzzle npm install
          docker compose up -d --wait
          docker compose exec -T kuzzle npm run test:functional --prefix plugin

          exitcode="$?"
          [[ "$exitcode" == "0" ]] || docker compose logs kuzzle
          exit "$exitcode"

  release-device-manager:
    name: Release package
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/2-stable' || github.ref == 'refs/heads/2-beta' || github.ref == 'refs/heads/3-dev' || github.ref == 'refs/heads/2-dev') }}
    needs: [functional-tests]
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --prefix plugin

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GHP }}
          SEMANTIC_RELEASE_NPM_PUBLISH: 'true'
          SEMANTIC_RELEASE_SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
        run: npx semantic-release

  documentation_deploy:
    needs: [release-device-manager]
    name: Documentation - Deploy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_CI }}

      - name: Extract references from context
        shell: bash
        id: extract-refs
        run: |
          version=$(jq -r .version package.json | cut -d. -f 1)
          echo "major-version=$(($version == 0 ? 1 : $version))" >> $GITHUB_OUTPUT
          echo "repo=$(echo $GITHUB_REPOSITORY | cut -d/ -f 2)" >> $GITHUB_OUTPUT

      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: kuzzleio
          repo: documentation
          github_token: ${{ secrets.ACCESS_TOKEN_CI }}
          workflow_file_name: child_repo.workflow.yml
          ref: ${{ github.ref_name == '2-stable' && '2-stable' || '2-dev' }}
          client_payload: '{"repo_name":"${{ steps.extract-refs.outputs.repo }}","branch":"${{ github.ref_name }}","version":"${{ steps.extract-refs.outputs.major-version }}"}'
